trigger:
- main

# trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: Foo1
  steps:
  - script: echo Hello!

- job: Foo2
  steps:
  - script: echo Hello!

- job: Foo3
  steps:
  - script: echo Hello!